version: '3.9'
services:
  server:
    build: .
    container_name: voice-server
    environment:
      - OPENROUTER_ENABLED=true
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NODE_ENV=production
    ports:
      - '3030:3030'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3030/health']
      interval: 30s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
